services:
  - type: web
      name: drawpile-server
          env:  docker
              plan: free
                  dockerfilePath: ./Dockerfile
                      envVars:
                            - key:  PORT
                                    value: 27750